services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.nju.edu.cn/home-assistant/home-assistant:stable
    volumes:
      - ${AUTUMN_HA_CONFIG:?set AUTUMN_HA_CONFIG}:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: ${TZ:-Asia/Shanghai}
