import assert from "node:assert/strict";
import test from "node:test";
import { validateCheckpointPreview, confirmCheckpoint, unavailableGitProvider } from "./ysyx_git_provider.mjs";

const base = { message: "checkpoint: D1 RV32M stable tests pass", tree_fingerprint: "fixture-tree" };
test("unavailable provider is explicit and cannot execute", async () => { assert.equal((await unavailableGitProvider().status()).status, "unavailable"); });
test("mark_current_state contract permits empty paths and produces allow-empty argv only", () => { const result = validateCheckpointPreview({ ...base, mode: "mark_current_state", paths: [] }); assert.equal(result.ok, true); const confirmed = confirmCheckpoint(result.preview, { confirmation_id: result.preview.confirmation_id, mode: "mark_current_state", message: base.message, paths: [], tree_fingerprint: "fixture-tree" }); assert.equal(confirmed.code, "PROVIDER_UNAVAILABLE"); assert.deepEqual(confirmed.operations[0].argv.slice(0, 3), ["git", "commit", "--allow-empty"]); });
test("commit_changes requires explicit safe paths", () => { assert.equal(validateCheckpointPreview({ ...base, mode: "commit_changes", paths: [] }).ok, false); assert.equal(validateCheckpointPreview({ ...base, mode: "commit_changes", paths: ["../x"] }).ok, false); assert.equal(validateCheckpointPreview({ ...base, mode: "commit_changes", paths: ["nemu/src/isa.c"] }).ok, true); });
test("confirmation missing, expired, or mismatched is refused", () => { const made = validateCheckpointPreview({ ...base, mode: "commit_changes", paths: ["nemu/a.c"] }).preview; assert.equal(confirmCheckpoint(made, null).code, "CONFIRMATION_REQUIRED"); assert.equal(confirmCheckpoint(made, { confirmation_id: made.confirmation_id, mode: "commit_changes", message: base.message, paths: ["nemu/a.c"], tree_fingerprint: "other" }).code, "CONFIRMATION_MISMATCH"); const expired = validateCheckpointPreview({ ...base, mode: "mark_current_state", paths: [] }).preview; assert.equal(confirmCheckpoint(expired, { confirmation_id: expired.confirmation_id, mode: expired.mode, message: base.message, paths: [], tree_fingerprint: "fixture-tree" }, { now: expired.expires_at + 1 }).code, "CONFIRMATION_EXPIRED"); });
